---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.04, CPAN::Meta::Converter version 2.143240'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: RPerl
no_index:
  directory:
    - t
    - inc
requires:
  Inline: '0.76'
  Inline::C: '0.64'
  Inline::CPP: '0.63'
  Inline::Filters: '0.16'
  Parse::Eyapp: '1.182'
  Perl::Critic: '1.121'
  Perl::Tidy: '20140711'
  Test::Exception: '0.32'
version: '1.000002'
